server:
  port: 8070

spring:
  # JPA 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        show_sql: true        # 쿼리 로그 출력
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        use_sql_comments: true
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    # DEV
#    url: jdbc:log4jdbc:mysql://https://juniza82.synology.me:33077/community?useMysqlMetadata=true
    url: jdbc:log4jdbc:mariadb://juniza82.synology.me:33077/community?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useMysqlMetadata=true
    username: juniza82
    password: Lej281500!@
    # elasticsearch:
#    uris: 3.34.190.160:9201
#    username: admin
#    password: admin
    hikari:
      maximum-pool-size: 5
      connection-timeout: 3000
#  autoconfigure:
#    exclude: org.opensearch.spring.boot.autoconfigure.OpenSearchRestClientAutoConfiguration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  codec:
    max-in-memory-size: 4096
#  data:
#    mongodb:
#      uri: mongodb://3.34.190.160:27018/expedia
#    redis:
#      host: 3.34.190.160
#      port: 6380
#      database: 15
#    lettuce:
#      pool:
#        min-idle: 1
#        max-idle: 8
#        max-active: 8
#        max-wait: 2000ms

  main:
    allow-bean-definition-overriding: true

api:
  expedia:
    url: https://test.ean.com
    key: 3oemj3md0t5evnb9tubrad4ift
    secret-key: 5vqg56m7ao12g

springdoc:
  swagger-ui:
    version: v1
    path: /swagger-ui.html
    enabled: true
  paths-to-exclude:
    - /test/**
    - /dev/**
    - /settings/**
    - /redis/**

jwt:
  secret-key: BMXDcZQGBFnKNYCYRgsIxiFQR

aes:
  key: COMMUNITY_KEY_12345
  iv: COMMUNITY_IV_12345

logging:
  level:
    root: info
#  slack:
#    channel: hotel-error
#    webhook-uri: https://hooks.slack.com/services/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
#    channel-hotel-reservation: hotel-reservation-bot
#    reservation-webhook-uri: https://hooks.slack.com/services/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
