spring:
  security:
    filter:
      order: 10 # for logging filter
    user:
      name: community
      password: community
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    version: v2
    path: /swagger-ui.html
    enabled: true
  paths-to-exclude:
    - /test/**
    - /dev/**
    - /settings/**
    - /redis/**






